In [30]:
import numpy as np
import pandas as pd

In [31]:
numbers = np.random.randint(100, 500, size=(4, 7))
print(numbers)

[[140 210 476 356 305 359 106]
 [155 175 273 288 107 152 108]
 [119 263 332 380 287 227 408]
 [447 390 415 401 246 245 147]]


In [32]:
numbers = np.where(numbers > 300, numbers * 1.1, numbers)
print(numbers)

[[140.  210.  523.6 391.6 335.5 394.9 106. ]
 [155.  175.  273.  288.  107.  152.  108. ]
 [119.  263.  365.2 418.  287.  227.  448.8]
 [491.7 429.  456.5 441.1 246.  245.  147. ]]


In [33]:
numbers = np.where(numbers < 300, numbers * .95, numbers)
print(numbers)

[[133.   199.5  523.6  391.6  335.5  394.9  100.7 ]
 [147.25 166.25 259.35 273.6  101.65 144.4  102.6 ]
 [113.05 249.85 365.2  418.   272.65 215.65 448.8 ]
 [491.7  429.   456.5  441.1  233.7  232.75 139.65]]


In [34]:
np.average(numbers[:,-2:])

222.43124999999998

In [35]:
numbers>400

array([[False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False,  True, False, False,  True],
       [ True,  True,  True,  True, False, False, False]])

In [36]:
df = pd.DataFrame(numbers, columns=['A', 'B', 'C', 'D', 'E', 'F', 'G'])
df.head()

A       B       C      D       E       F       G
0  133.00  199.50  523.60  391.6  335.50  394.90  100.70
1  147.25  166.25  259.35  273.6  101.65  144.40  102.60
2  113.05  249.85  365.20  418.0  272.65  215.65  448.80
3  491.70  429.00  456.50  441.1  233.70  232.75  139.65